import MiProvider from "@/store/provider";
import { Montserrat } from "next/font/google";
import Carrito from "./carrito/Carrito"


const fuente = Montserrat({
  weight: '400',
  subsets: ['latin']
})

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <MiProvider>
        <body className={fuente.className}>
          <Carrito />
          <div>
            {children}
          </div>
        </body>
      </MiProvider>
    </html>
  )
}
